dataformCoreVersion: 3.0.47
defaultProject: drawingfire-b72a8
defaultDataset: football_data
vars: {
    "tableDescription": "something amazing",
    "dummyColumnValue": "43"
}
defaultAssertionDataset: football_data
defaultNotebookRuntimeOptions:
  outputBucket: "gs://dataform-notebooks"
