config {
  type: 'table',
  assertions: {
    uniqueKey: ["UUID"]
  },
  tags: ["nested"]
}


WITH CTE AS (
  SELECT
    GENERATE_UUID()                                  AS UUID
    , "ALL_DATA"                                     AS FOO
    , 129                                            AS NUMBER_COLUMN
    , ARRAY<STRING>["STRING1", "STRING2", "STRING3"] AS STRINGARRAY
    , ARRAY(
      SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 5)) AS POPULATEDARRAYMOREITEMS
    )                                                AS POPULATEDARRAYMOREITEMS
    , ARRAY(
      SELECT AS STRUCT * FROM UNNEST(GENERATE_DATE_ARRAY(CURRENT_DATE(), CURRENT_DATE() + 6, INTERVAL 1 DAY)) AS DATEARRAY
    )                                                AS DATEARRAY
  FROM UNNEST(GENERATE_ARRAY(1, 2)) AS ID
)

SELECT * FROM CTE
